-- Users Table: Stores user account information.
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Websites Table: Stores websites registered by users to be tracked.
CREATE TABLE websites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Sessions Table: Stores individual user sessions.
CREATE TABLE sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_session_id VARCHAR(255) UNIQUE NOT NULL, -- The ID generated by the client tracker.js
    website_id UUID NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    user_agent TEXT,
    browser VARCHAR(50),
    os VARCHAR(50),
    device VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Click Events Table: Stores individual click events from the tracker.
CREATE TABLE click_events (
    id BIGSERIAL PRIMARY KEY,
    website_id UUID NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    x INT NOT NULL,
    y INT NOT NULL,
    viewport_width INT NOT NULL,
    viewport_height INT NOT NULL,
    url VARCHAR(2048) NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT now()
);

-- Mouse Move Events Table: Stores batches of mouse movement coordinates.
CREATE TABLE mousemove_events (
    id BIGSERIAL PRIMARY KEY,
    website_id UUID NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    points JSONB NOT NULL,
    url VARCHAR(2048) NOT NULL,
    viewport_width INT NOT NULL,
    viewport_height INT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT now()
);

-- Create indexes for faster queries
CREATE INDEX idx_websites_user_id ON websites(user_id);
CREATE INDEX idx_sessions_website_id ON sessions(website_id);
CREATE INDEX idx_click_events_website_id ON click_events(website_id);
CREATE INDEX idx_click_events_session_id ON click_events(session_id);
CREATE INDEX idx_click_events_timestamp ON click_events(timestamp);
CREATE INDEX idx_mousemove_events_website_id ON mousemove_events(website_id);
CREATE INDEX idx_mousemove_events_session_id ON mousemove_events(session_id);
CREATE INDEX idx_mousemove_events_timestamp ON mousemove_events(timestamp);

-- Performance Metrics Table: Stores Core Web Vitals and other performance data.
CREATE TABLE performance_metrics (
    id BIGSERIAL PRIMARY KEY,
    website_id UUID NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    metric_name VARCHAR(50) NOT NULL, -- e.g., 'LCP', 'FID', 'CLS'
    value NUMERIC NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT now()
);

-- JavaScript Errors Table: Stores errors caught from the client-side.
CREATE TABLE js_errors (
    id BIGSERIAL PRIMARY KEY,
    website_id UUID NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    error_message TEXT NOT NULL,
    stack_trace TEXT,
    timestamp TIMESTAMPTZ DEFAULT now()
);

-- Create indexes for new tables
CREATE INDEX idx_performance_metrics_website_id ON performance_metrics(website_id);
CREATE INDEX idx_js_errors_website_id ON js_errors(website_id);